version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:



#Starta: docker compose up -d
#Stoppa: docker compose down
#Stoppa & ta bort all data: docker compose down -v
#Visa loggar: docker compose logs -f
#Kör kommandon i container: docker compose exec <service> <kommando>
#Byt miljö: docker compose --env-file .env.test up
#Kommando för köra allt i docker även testerna 
#docker compose up --build
#docker compose exec app npm test