version: '3.8'
services:
  app:
    build: .
    container_name: almgruppuppgift_app
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - PORT=3000
    volumes:
      - .:/usr/src/app
      - ./db-data:/usr/src/app/database  
    command: npm start

